"""initial schema

Revision ID: 9874811a8696
Revises: 
Create Date: 2026-07-22 21:36:37.683463
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9874811a8696'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decoration_ideas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('budget', sa.Numeric(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regulation_note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neighborhoods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('score_overall', sa.Numeric(), nullable=False),
    sa.Column('score_securite', sa.Numeric(), nullable=False),
    sa.Column('score_transport', sa.Numeric(), nullable=False),
    sa.Column('score_bruit', sa.Numeric(), nullable=False),
    sa.Column('score_commerces', sa.Numeric(), nullable=False),
    sa.Column('score_ecoles', sa.Numeric(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(), nullable=True),
    sa.Column('trend', sa.Enum('hausse', 'stable', 'baisse', name='neighborhood_trend'), nullable=False),
    sa.Column('price_per_sqm', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staging_examples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('before_url', sa.String(), nullable=True),
    sa.Column('after_url', sa.String(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(), nullable=True),
    sa.Column('value_gain', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('vendeur', 'acheteur', 'investisseur', name='user_role'), nullable=False),
    sa.Column('member_since', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Numeric(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('coloc_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('budget', sa.Numeric(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coloc_profiles_user_id'), 'coloc_profiles', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('offre_similaire', 'message', 'prix', 'visite', 'systeme', 'alerte', name='notification_kind'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('href', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('points_of_interest',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('neighborhood_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('ecole', 'universite', 'transport', 'commerce', 'parc', 'hopital', 'bruit', 'pollution', 'embouteillage', name='poi_kind'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('position_x', sa.Numeric(), nullable=False),
    sa.Column('position_y', sa.Numeric(), nullable=False),
    sa.Column('distance_min', sa.Integer(), nullable=False),
    sa.Column('negative', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('appartement', 'maison', 'studio', 'loft', 'duplex', 'immeuble', name='property_type'), nullable=False),
    sa.Column('transaction', sa.Enum('vente', 'location', name='transaction_type'), nullable=False),
    sa.Column('status', sa.Enum('disponible', 'sous_offre', 'loue', 'vendu', 'brouillon', 'en_verification', name='property_status'), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('charges', sa.Numeric(), nullable=True),
    sa.Column('surface', sa.Numeric(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('energy_class', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', name='energy_class'), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('neighborhood_id', sa.Uuid(), nullable=True),
    sa.Column('position_x', sa.Numeric(), nullable=True),
    sa.Column('position_y', sa.Numeric(), nullable=True),
    sa.Column('source', sa.Enum('plateforme', 'web', name='property_source'), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('honesty_score', sa.Integer(), nullable=True),
    sa.Column('ai_price_estimate', sa.Numeric(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('favorite_count', sa.Integer(), nullable=False),
    sa.Column('availability_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('alert_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('abuse_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('scam', 'comportement', name='abuse_kind'), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('en_cours', 'traite', name='abuse_status'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abuse_reports_property_id'), 'abuse_reports', ['property_id'], unique=False)
    op.create_index(op.f('ix_abuse_reports_reporter_id'), 'abuse_reports', ['reporter_id'], unique=False)
    op.create_table('competitor_listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('surface', sa.Numeric(), nullable=False),
    sa.Column('price_per_sqm', sa.Numeric(), nullable=False),
    sa.Column('distance_km', sa.Numeric(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    # property_source type is already created by the `properties` table above.
    sa.Column(
        'source',
        sa.Enum('plateforme', 'web', name='property_source', create_type=False),
        nullable=False,
    ),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_listings_property_id'), 'competitor_listings', ['property_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('last_message', sa.String(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_property_id'), 'conversations', ['property_id'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'property_id')
    )
    op.create_table('generated_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_issues', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_contracts_property_id'), 'generated_contracts', ['property_id'], unique=False)
    op.create_table('investment_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gross_yield', sa.Numeric(), nullable=True),
    sa.Column('net_yield', sa.Numeric(), nullable=True),
    sa.Column('monthly_rent', sa.Numeric(), nullable=True),
    sa.Column('annual_costs', sa.Numeric(), nullable=True),
    sa.Column('cashflow', sa.Numeric(), nullable=True),
    sa.Column('payback_years', sa.Numeric(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('forecast_now', sa.Numeric(), nullable=True),
    sa.Column('forecast_5y', sa.Numeric(), nullable=True),
    sa.Column('forecast_10y', sa.Numeric(), nullable=True),
    sa.Column('annual_growth_percent', sa.Numeric(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_reports_property_id'), 'investment_reports', ['property_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('en_attente', 'acceptee', 'refusee', 'expiree', name='offer_status'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_buyer_id'), 'offers', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_offers_property_id'), 'offers', ['property_id'], unique=False)
    op.create_table('property_features',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('property_id', 'feature')
    )
    op.create_table('property_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('photo', 'video', 'virtual_tour', 'floor_plan', name='media_kind'), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_media_property_id'), 'property_media', ['property_id'], unique=False)
    op.create_table('repair_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('issue', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', name='issue_severity'), nullable=False),
    sa.Column('estimated_cost_min', sa.Numeric(), nullable=True),
    sa.Column('estimated_cost_max', sa.Numeric(), nullable=True),
    sa.Column('score_impact', sa.Numeric(), nullable=True),
    sa.Column('price_impact', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_findings_property_id'), 'repair_findings', ['property_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_author_id'), 'reviews', ['author_id'], unique=False)
    op.create_index(op.f('ix_reviews_property_id'), 'reviews', ['property_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('risk_factors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('faible', 'modere', 'eleve', name='risk_level'), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['investment_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_factors_report_id'), 'risk_factors', ['report_id'], unique=False)
    op.create_table('what_if_scenarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('delta_yield', sa.Numeric(), nullable=True),
    sa.Column('delta_value', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['investment_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_what_if_scenarios_report_id'), 'what_if_scenarios', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_what_if_scenarios_report_id'), table_name='what_if_scenarios')
    op.drop_table('what_if_scenarios')
    op.drop_index(op.f('ix_risk_factors_report_id'), table_name='risk_factors')
    op.drop_table('risk_factors')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_reviews_property_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_author_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_repair_findings_property_id'), table_name='repair_findings')
    op.drop_table('repair_findings')
    op.drop_index(op.f('ix_property_media_property_id'), table_name='property_media')
    op.drop_table('property_media')
    op.drop_table('property_features')
    op.drop_index(op.f('ix_offers_property_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_buyer_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_investment_reports_property_id'), table_name='investment_reports')
    op.drop_table('investment_reports')
    op.drop_index(op.f('ix_generated_contracts_property_id'), table_name='generated_contracts')
    op.drop_table('generated_contracts')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_conversations_property_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_competitor_listings_property_id'), table_name='competitor_listings')
    op.drop_table('competitor_listings')
    op.drop_index(op.f('ix_abuse_reports_reporter_id'), table_name='abuse_reports')
    op.drop_index(op.f('ix_abuse_reports_property_id'), table_name='abuse_reports')
    op.drop_table('abuse_reports')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_table('points_of_interest')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_coloc_profiles_user_id'), table_name='coloc_profiles')
    op.drop_table('coloc_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('staging_examples')
    op.drop_table('neighborhoods')
    op.drop_table('decoration_ideas')
    # ### end Alembic commands ###
